on: [push]
jobs:
  BuildPDF:
    runs-on: ubuntu-20.04
    name: Build PDF from .tex
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build PDF builder
        run: docker build -t pdfbuilder .
      - name: Build PDF
        run: docker run --mount src=`pwd`/cv,target=/cv,type=bind pdfbuilder
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: cv/resume.pdf
          retention-days: 1

  PublishPDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download resume from builder
        uses: actions/download-artifact@v2
        with:
          name: resume
      - name: Commit report
        run: |
          git config --global user.name 'Aleksandr Draganov'
          git config --global user.email 'nomapunk@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add resume.pdf
          git commit -m "CI resume"
          git push
